export interface QuantInfo {
  name: "Q2_K" | "Q3_K_M" | "Q4_K_M" | "Q5_K_M" | "Q6_K" | "Q8_0" | "F16";
  vramGb: number;
}

export interface LocalHardwareModel {
  id: string;
  name: string;
  slug: string;
  provider: string;
  paramsNum: number; // Billions (e.g. 3, 7, 8, 9, 14, 32, 70)
  paramsText: string; // e.g. "9B params"
  qualityScore: number; // 0 - 100
  contextWindow: string; // e.g. "128K ctx"
  license: string; // e.g. "Apache 2.0"
  description: string;
  tags: string[]; // e.g. ["CHAT", "CODE", "REASONING", "VISION"]
  quants: QuantInfo[];
}

export interface HardwarePreset {
  id: string;
  name: string;
  vramGb: number;
  bandwidthGbs: number;
  isUnified: boolean;
}

export const HARDWARE_PRESETS: HardwarePreset[] = [
  { id: "apple-m1-8", name: "Apple M1 (8 GB)", vramGb: 8, bandwidthGbs: 100, isUnified: true },
  { id: "apple-m2-16", name: "Apple M2 (16 GB)", vramGb: 16, bandwidthGbs: 150, isUnified: true },
  { id: "apple-m3-pro-36", name: "Apple M3 Pro (36 GB)", vramGb: 36, bandwidthGbs: 300, isUnified: true },
  { id: "apple-m3-max-64", name: "Apple M3 Max (64 GB)", vramGb: 64, bandwidthGbs: 400, isUnified: true },
  { id: "apple-m4-max-128", name: "Apple M4 Max (128 GB)", vramGb: 128, bandwidthGbs: 800, isUnified: true },
  { id: "rtx-3060-12", name: "NVIDIA RTX 3060 (12 GB)", vramGb: 12, bandwidthGbs: 360, isUnified: false },
  { id: "rtx-4070ti-12", name: "NVIDIA RTX 4070 Ti (12 GB)", vramGb: 12, bandwidthGbs: 504, isUnified: false },
  { id: "rtx-4080-16", name: "NVIDIA RTX 4080 (16 GB)", vramGb: 16, bandwidthGbs: 716, isUnified: false },
  { id: "rtx-4090-24", name: "NVIDIA RTX 4090 (24 GB)", vramGb: 24, bandwidthGbs: 1008, isUnified: false },
  { id: "dual-rtx-4090-48", name: "2x NVIDIA RTX 4090 (48 GB)", vramGb: 48, bandwidthGbs: 2016, isUnified: false },
  { id: "rtx-6000-ada-48", name: "NVIDIA RTX 6000 Ada (48 GB)", vramGb: 48, bandwidthGbs: 960, isUnified: false },
  { id: "nvidia-a100-80", name: "NVIDIA A100 (80 GB)", vramGb: 80, bandwidthGbs: 2039, isUnified: false },
  { id: "rx-7900-xtx-24", name: "AMD Radeon RX 7900 XTX (24 GB)", vramGb: 24, bandwidthGbs: 960, isUnified: false },
  { id: "cpu-only", name: "CPU Only / System RAM", vramGb: 0, bandwidthGbs: 50, isUnified: false },
];

export const SYSTEM_RAM_OPTIONS = [8, 16, 32, 48, 64, 96, 128, 256];
export const CPU_CORE_OPTIONS = [4, 8, 12, 16, 24, 32];

export const LOCAL_MODELS_DATASET: LocalHardwareModel[] = [
  {
    id: "smollm3-3b",
    name: "SmolLM3 3B",
    slug: "smollm3-3b",
    provider: "HuggingFace",
    paramsNum: 3,
    paramsText: "3B params",
    qualityScore: 65,
    contextWindow: "128K ctx",
    license: "Apache 2.0",
    description: "Lightweight multilingual reasoning model for edge hardware",
    tags: ["CHAT", "REASONING", "EDGE"],
    quants: [
      { name: "Q2_K", vramGb: 1.0 },
      { name: "Q3_K_M", vramGb: 1.4 },
      { name: "Q4_K_M", vramGb: 1.9 },
      { name: "Q5_K_M", vramGb: 2.3 },
      { name: "Q6_K", vramGb: 2.7 },
      { name: "Q8_0", vramGb: 3.3 },
      { name: "F16", vramGb: 6.6 },
    ],
  },
  {
    id: "llama-3-2-3b",
    name: "Llama 3.2 3B",
    slug: "llama-3-2-3b",
    provider: "Meta",
    paramsNum: 3,
    paramsText: "3B params",
    qualityScore: 68,
    contextWindow: "128K ctx",
    license: "Llama 3.2",
    description: "Lightweight Llama model optimized for mobile and edge devices",
    tags: ["CHAT", "CODE"],
    quants: [
      { name: "Q2_K", vramGb: 1.0 },
      { name: "Q3_K_M", vramGb: 1.4 },
      { name: "Q4_K_M", vramGb: 1.9 },
      { name: "Q5_K_M", vramGb: 2.3 },
      { name: "Q6_K", vramGb: 2.7 },
      { name: "Q8_0", vramGb: 3.3 },
      { name: "F16", vramGb: 6.6 },
    ],
  },
  {
    id: "qwen-3-5-2b",
    name: "Qwen 3.5 2B",
    slug: "qwen-3-5-2b",
    provider: "Alibaba",
    paramsNum: 2,
    paramsText: "2B params",
    qualityScore: 62,
    contextWindow: "32K ctx",
    license: "Apache 2.0",
    description: "Small multimodal Qwen 3.5 model with ultra-fast generation",
    tags: ["CHAT", "MULTILINGUAL"],
    quants: [
      { name: "Q2_K", vramGb: 0.7 },
      { name: "Q3_K_M", vramGb: 1.0 },
      { name: "Q4_K_M", vramGb: 1.2 },
      { name: "Q5_K_M", vramGb: 1.5 },
      { name: "Q6_K", vramGb: 1.8 },
      { name: "Q8_0", vramGb: 2.2 },
      { name: "F16", vramGb: 4.4 },
    ],
  },
  {
    id: "deepseek-r1-1-5b",
    name: "DeepSeek R1 1.5B",
    slug: "deepseek-r1-1-5b",
    provider: "DeepSeek",
    paramsNum: 1.5,
    paramsText: "1.5B params",
    qualityScore: 66,
    contextWindow: "128K ctx",
    license: "MIT",
    description: "Compact reasoning model distilled from DeepSeek-R1",
    tags: ["REASONING", "CODE"],
    quants: [
      { name: "Q2_K", vramGb: 0.6 },
      { name: "Q3_K_M", vramGb: 0.8 },
      { name: "Q4_K_M", vramGb: 1.1 },
      { name: "Q5_K_M", vramGb: 1.3 },
      { name: "Q6_K", vramGb: 1.5 },
      { name: "Q8_0", vramGb: 1.8 },
      { name: "F16", vramGb: 3.3 },
    ],
  },
  {
    id: "qwen-3-5-9b",
    name: "Qwen 3.5 9B",
    slug: "qwen-3-5-9b",
    provider: "Alibaba",
    paramsNum: 9,
    paramsText: "9B params",
    qualityScore: 78,
    contextWindow: "128K ctx",
    license: "Apache 2.0",
    description: "Multimodal Qwen 3.5 mid-size model for general reasoning and code",
    tags: ["CHAT", "CODE", "VISION", "MULTIMODAL"],
    quants: [
      { name: "Q2_K", vramGb: 2.8 },
      { name: "Q3_K_M", vramGb: 4.1 },
      { name: "Q4_K_M", vramGb: 5.4 },
      { name: "Q5_K_M", vramGb: 6.6 },
      { name: "Q6_K", vramGb: 7.8 },
      { name: "Q8_0", vramGb: 9.8 },
      { name: "F16", vramGb: 19.2 },
    ],
  },
  {
    id: "llama-3-1-8b",
    name: "Llama 3.1 8B",
    slug: "llama-3-1-8b",
    provider: "Meta",
    paramsNum: 8,
    paramsText: "8B params",
    qualityScore: 76,
    contextWindow: "128K ctx",
    license: "Llama 3.1",
    description: "State-of-the-art 8B open model for chat, coding, and function calling",
    tags: ["CHAT", "CODE", "AGENTIC"],
    quants: [
      { name: "Q2_K", vramGb: 2.6 },
      { name: "Q3_K_M", vramGb: 3.7 },
      { name: "Q4_K_M", vramGb: 4.9 },
      { name: "Q5_K_M", vramGb: 5.9 },
      { name: "Q6_K", vramGb: 7.0 },
      { name: "Q8_0", vramGb: 8.8 },
      { name: "F16", vramGb: 17.2 },
    ],
  },
  {
    id: "qwen-2-5-coder-7b",
    name: "Qwen 2.5 Coder 7B",
    slug: "qwen-2-5-coder-7b",
    provider: "Alibaba",
    paramsNum: 7,
    paramsText: "7B params",
    qualityScore: 77,
    contextWindow: "128K ctx",
    license: "Apache 2.0",
    description: "Specialized code generation model with impressive benchmark performance",
    tags: ["CODE", "AGENTIC"],
    quants: [
      { name: "Q2_K", vramGb: 2.3 },
      { name: "Q3_K_M", vramGb: 3.3 },
      { name: "Q4_K_M", vramGb: 4.4 },
      { name: "Q5_K_M", vramGb: 5.3 },
      { name: "Q6_K", vramGb: 6.2 },
      { name: "Q8_0", vramGb: 7.8 },
      { name: "F16", vramGb: 15.2 },
    ],
  },
  {
    id: "deepseek-r1-distill-14b",
    name: "DeepSeek R1 14B",
    slug: "deepseek-r1-distill-14b",
    provider: "DeepSeek",
    paramsNum: 14,
    paramsText: "14B params",
    qualityScore: 83,
    contextWindow: "128K ctx",
    license: "MIT",
    description: "Mid-size reasoning distilled model with chain-of-thought capabilities",
    tags: ["REASONING", "CODE", "AGENTIC"],
    quants: [
      { name: "Q2_K", vramGb: 4.5 },
      { name: "Q3_K_M", vramGb: 6.4 },
      { name: "Q4_K_M", vramGb: 8.5 },
      { name: "Q5_K_M", vramGb: 10.2 },
      { name: "Q6_K", vramGb: 12.1 },
      { name: "Q8_0", vramGb: 15.1 },
      { name: "F16", vramGb: 29.5 },
    ],
  },
  {
    id: "gemma-2-9b",
    name: "Gemma 2 9B",
    slug: "gemma-2-9b",
    provider: "Google",
    paramsNum: 9,
    paramsText: "9B params",
    qualityScore: 77,
    contextWindow: "8K ctx",
    license: "Gemma License",
    description: "Google's 9B open model with high math and reasoning density",
    tags: ["CHAT", "REASONING"],
    quants: [
      { name: "Q2_K", vramGb: 2.9 },
      { name: "Q3_K_M", vramGb: 4.2 },
      { name: "Q4_K_M", vramGb: 5.5 },
      { name: "Q5_K_M", vramGb: 6.7 },
      { name: "Q6_K", vramGb: 7.9 },
      { name: "Q8_0", vramGb: 9.9 },
      { name: "F16", vramGb: 19.5 },
    ],
  },
  {
    id: "mistral-7b-v0-3",
    name: "Mistral 7B v0.3",
    slug: "mistral-7b-v0-3",
    provider: "Mistral AI",
    paramsNum: 7,
    paramsText: "7B params",
    qualityScore: 74,
    contextWindow: "32K ctx",
    license: "Apache 2.0",
    description: "Classic open-weights model with function calling and sliding window attention",
    tags: ["CHAT", "CODE", "RAG"],
    quants: [
      { name: "Q2_K", vramGb: 2.3 },
      { name: "Q3_K_M", vramGb: 3.3 },
      { name: "Q4_K_M", vramGb: 4.3 },
      { name: "Q5_K_M", vramGb: 5.2 },
      { name: "Q6_K", vramGb: 6.1 },
      { name: "Q8_0", vramGb: 7.7 },
      { name: "F16", vramGb: 15.0 },
    ],
  },
  {
    id: "phi-3-5-mini-3-8b",
    name: "Phi-3.5 Mini 3.8B",
    slug: "phi-3-5-mini-3-8b",
    provider: "Microsoft",
    paramsNum: 3.8,
    paramsText: "3.8B params",
    qualityScore: 71,
    contextWindow: "128K ctx",
    license: "MIT",
    description: "Highly optimized 3.8B model for long-context comprehension and logic",
    tags: ["REASONING", "CODE"],
    quants: [
      { name: "Q2_K", vramGb: 1.3 },
      { name: "Q3_K_M", vramGb: 1.8 },
      { name: "Q4_K_M", vramGb: 2.4 },
      { name: "Q5_K_M", vramGb: 2.9 },
      { name: "Q6_K", vramGb: 3.4 },
      { name: "Q8_0", vramGb: 4.2 },
      { name: "F16", vramGb: 8.2 },
    ],
  },
  {
    id: "qwen-2-5-coder-32b",
    name: "Qwen 2.5 Coder 32B",
    slug: "qwen-2-5-coder-32b",
    provider: "Alibaba",
    paramsNum: 32,
    paramsText: "32B params",
    qualityScore: 88,
    contextWindow: "128K ctx",
    license: "Apache 2.0",
    description: "Frontier 32B code model matching Sonnet 3.5 in coding benchmarks",
    tags: ["CODE", "AGENTIC", "REASONING"],
    quants: [
      { name: "Q2_K", vramGb: 10.2 },
      { name: "Q3_K_M", vramGb: 14.6 },
      { name: "Q4_K_M", vramGb: 19.4 },
      { name: "Q5_K_M", vramGb: 23.5 },
      { name: "Q6_K", vramGb: 27.6 },
      { name: "Q8_0", vramGb: 34.5 },
      { name: "F16", vramGb: 68.0 },
    ],
  },
  {
    id: "deepseek-r1-distill-32b",
    name: "DeepSeek R1 32B",
    slug: "deepseek-r1-distill-32b",
    provider: "DeepSeek",
    paramsNum: 32,
    paramsText: "32B params",
    qualityScore: 89,
    contextWindow: "128K ctx",
    license: "MIT",
    description: "32B reasoning model distilled from Qwen 32B with R1 chain-of-thought",
    tags: ["REASONING", "CODE"],
    quants: [
      { name: "Q2_K", vramGb: 10.2 },
      { name: "Q3_K_M", vramGb: 14.6 },
      { name: "Q4_K_M", vramGb: 19.4 },
      { name: "Q5_K_M", vramGb: 23.5 },
      { name: "Q6_K", vramGb: 27.6 },
      { name: "Q8_0", vramGb: 34.5 },
      { name: "F16", vramGb: 68.0 },
    ],
  },
  {
    id: "llama-3-3-70b",
    name: "Llama 3.3 70B",
    slug: "llama-3-3-70b",
    provider: "Meta",
    paramsNum: 70,
    paramsText: "70B params",
    qualityScore: 93,
    contextWindow: "128K ctx",
    license: "Llama 3.3",
    description: "Meta's flagship 70B open weight model for enterprise agentic intelligence",
    tags: ["CHAT", "CODE", "REASONING", "AGENTIC"],
    quants: [
      { name: "Q2_K", vramGb: 22.5 },
      { name: "Q3_K_M", vramGb: 32.1 },
      { name: "Q4_K_M", vramGb: 42.5 },
      { name: "Q5_K_M", vramGb: 51.5 },
      { name: "Q6_K", vramGb: 60.5 },
      { name: "Q8_0", vramGb: 75.5 },
      { name: "F16", vramGb: 148.0 },
    ],
  },
  {
    id: "deepseek-r1-70b",
    name: "DeepSeek R1 70B",
    slug: "deepseek-r1-70b",
    provider: "DeepSeek",
    paramsNum: 70,
    paramsText: "70B params",
    qualityScore: 94,
    contextWindow: "128K ctx",
    license: "MIT",
    description: "70B reasoning powerhouse distilled from Llama 70B",
    tags: ["REASONING", "CODE", "AGENTIC"],
    quants: [
      { name: "Q2_K", vramGb: 22.5 },
      { name: "Q3_K_M", vramGb: 32.1 },
      { name: "Q4_K_M", vramGb: 42.5 },
      { name: "Q5_K_M", vramGb: 51.5 },
      { name: "Q6_K", vramGb: 60.5 },
      { name: "Q8_0", vramGb: 75.5 },
      { name: "F16", vramGb: 148.0 },
    ],
  },
  {
    id: "mixtral-8x7b",
    name: "Mixtral 8x7B 47B",
    slug: "mixtral-8x7b",
    provider: "Mistral AI",
    paramsNum: 47,
    paramsText: "47B params (MoE)",
    qualityScore: 84,
    contextWindow: "32K ctx",
    license: "Apache 2.0",
    description: "Sparse Mixture-of-Experts architecture (8x7B params, 13B active)",
    tags: ["CHAT", "CODE", "MULTILINGUAL"],
    quants: [
      { name: "Q2_K", vramGb: 15.1 },
      { name: "Q3_K_M", vramGb: 21.5 },
      { name: "Q4_K_M", vramGb: 28.4 },
      { name: "Q5_K_M", vramGb: 34.2 },
      { name: "Q6_K", vramGb: 40.1 },
      { name: "Q8_0", vramGb: 50.2 },
      { name: "F16", vramGb: 98.0 },
    ],
  },
];
