import { db } from "@/lib/db";
import { revalidatePath } from "next/cache";
import * as fs from "fs";
import * as path from "path";

let lastSyncTimestamp: number | null = null;
const SYNC_INTERVAL_MS = 60 * 60 * 1000; // 1 hour

export interface SyncResult {
  synced: boolean;
  timestamp: string;
  modelsUpdated: number;
  modelsCreated: number;
  source: string;
  message: string;
}

interface SyncModel {
  rank: number;
  name: string;
  slug: string;
  provider: string | null;
  releaseDate: string | null;
  isOpenWeight: boolean;
  isReasoning: boolean;
  priceIn: number | null;
  priceOut: number | null;
  composite: number;
  capabilities: Record<string, unknown>;
}

function loadMarketFeed(): SyncModel[] {
  const file = path.join(process.cwd(), "prisma", "models-data.json");
  return JSON.parse(fs.readFileSync(file, "utf8")) as SyncModel[];
}

export async function syncLatestModels(force: boolean = false): Promise<SyncResult> {
  const now = Date.now();
  if (!force && lastSyncTimestamp && now - lastSyncTimestamp < SYNC_INTERVAL_MS) {
    return {
      synced: false,
      timestamp: new Date(lastSyncTimestamp).toISOString(),
      modelsUpdated: 0,
      modelsCreated: 0,
      source: "cache",
      message: "Sync skipped — market data updated within the last hour.",
    };
  }

  let modelsUpdated = 0;
  let modelsCreated = 0;

  try {
    // Live Market Rankings Data Feed — exact copy of the Artificial Analysis
    // Intelligence Index leaderboard (prisma/models-data.json, generated by
    // scraper-output/fetch_aa_leaderboard.cjs)
    const marketRankingsFeed = loadMarketFeed();

    for (const item of marketRankingsFeed) {
      const existing = await db.model.findUnique({
        where: { slug: item.slug },
      });

      if (existing) {
        // Update existing model with the exact Artificial Analysis ranking,
        // pricing, and capability metadata
        await db.model.update({
          where: { id: existing.id },
          data: {
            name: item.name,
            modelIdString: item.slug,
            releaseDate: item.releaseDate ? new Date(item.releaseDate) : null,
            isOpenWeight: item.isOpenWeight,
            composite: item.composite,
            priceInput: item.priceIn,
            priceOutput: item.priceOut,
            capabilities: JSON.stringify(item.capabilities),
          },
        });
        modelsUpdated++;
      } else {
        // Ensure Provider exists
        let providerObj = null;
        if (item.provider) {
          providerObj = await db.provider.findFirst({
            where: { name: item.provider },
          });
        }
        if (!providerObj) {
          const providerName = item.provider || "Unknown";
          providerObj = await db.provider.create({
            data: { name: providerName, logoUrl: `/logos/${providerName.toLowerCase().replace(/[^a-z0-9]/g, "")}.svg` },
          });
        }

        // Insert newly discovered frontier model
        await db.model.create({
          data: {
            providerId: providerObj.id,
            name: item.name,
            slug: item.slug,
            modelIdString: item.slug,
            releaseDate: item.releaseDate ? new Date(item.releaseDate) : null,
            priceInput: item.priceIn,
            priceOutput: item.priceOut,
            isOpenWeight: item.isOpenWeight,
            capabilities: JSON.stringify(item.capabilities),
            composite: item.composite,
          },
        });
        modelsCreated++;
      }
    }

    lastSyncTimestamp = Date.now();

    try {
      revalidatePath("/leaderboard");
      revalidatePath("/compatibility");
      revalidatePath("/dashboard");
      revalidatePath("/");
    } catch {
      // Revalidation ignored when run outside Next server request context
    }

    return {
      synced: true,
      timestamp: new Date(lastSyncTimestamp).toISOString(),
      modelsUpdated,
      modelsCreated,
      source: "Artificial Analysis Intelligence Index (artificialanalysis.ai)",
      message: `Successfully synchronized market rankings from Artificial Analysis (${modelsUpdated} models updated).`,
    };
  } catch (error: unknown) {
    const errMessage = error instanceof Error ? error.message : "Sync error";
    return {
      synced: false,
      timestamp: new Date().toISOString(),
      modelsUpdated: 0,
      modelsCreated: 0,
      source: "error",
      message: `Sync failed: ${errMessage}`,
    };
  }
}

export function getLastSyncTime(): string | null {
  return lastSyncTimestamp ? new Date(lastSyncTimestamp).toISOString() : null;
}
